### PR TITLE
Editorial: Correctly introduce the variable A

### PR DESCRIPTION
**Pull request by nomeata**
which is used in the “state after” section

### CODE REVIEW

**Comment by jwiegley** [comment]
So for your review, does this look correct:
```coq
(** ** IC Management Canister: Canister creation

    Conditions: *)

Record canister_settings := {
  cs_controllers : Bag Principal;
  cs_compute_allocation : nat;
  cs_memory_allocation : nat;
  cs_freezing_threshold : nat;
}.

Hypothesis is_system_assigned : Principal -> bool.
Hypothesis CurrentTime : Timestamp.

Definition Mgmt_call_message
           (S : SystemState)
           Older_messages (M : CallMessageInfo) Younger_messages
           (name : string) `(A : ty) :=
    messages S = Older_messages ++ CallMessage M :: Younger_messages
  ∧ ( cm_queue M = Unordered
    ∨ (∀ msg, CallMessage msg ∈ Older_messages → cm_queue msg ≠ cm_queue M))
  ∧ cm_callee M = ic_principal
  ∧ cm_method_name M = name
  ∧ decodes_to (cm_data M) A.

Definition Mgmt_canister_creation
           (M : CallMessageInfo)
  : relation SystemState := λ S S',

    ∀ Older_messages Younger_messages (A : canister_settings),
      Mgmt_call_message S Older_messages M Younger_messages "create_canister" A
  ∧ ∀ CanisterId, is_system_assigned CanisterId = true
  ∧ CanisterId ∉ Keys (canisters S)

  (** State after, [S'] with: *)

  → CanisterId ↦ EmptyCanister ∈ canisters S'
  ∧ CanisterId ↦ CurrentTime ∈ canister_time S'
  ∧ (IF Same_set _ (cs_controllers A) (Empty_set _)
     then CanisterId ↦ Singleton _ (cm_caller M) ∈ controllers S'
     else CanisterId ↦ cs_controllers A ∈ controllers S')
  ∧ CanisterId ↦ cm_transferred_cycles M ∈ balances S'
  ∧ CanisterId ↦ "" ∈ certified_data S'
  ∧ ∃ R : Blob, decodes_to R {| cia_canister_id := CanisterId |}
  ∧ messages S' = Older_messages ++ Younger_messages ++
      ResponseMessage
        {| rm_origin          := cm_origin M
         ; rm_response        := Reply R
         ; rm_refunded_cycles := 0
         |} :: nil
  ∧ CanisterId ↦ CanRunning ∈ canister_status S'.
```

**Comment by nomeata** [comment]
Yes, although I am not sure what ties all the _other_, unchanged values of `S'` to `S` in this formulation of state transition (i.e. with predicates rather than saying `S' = some_modifications_to S`)

**Comment by jwiegley** [comment]
That's a really good point, @nomeata, I'll have to include that fact everywhere.

**Review by Dfinity-Bjoern — APPROVED** [review]
Thanks @nomeata

**Pull request merged**
