### PR TITLE
Public Spec: Optional backwards compatible name callbacks

### PR DESCRIPTION
**Pull request by levifeldman**
This is a follow on PR to https://github.com/dfinity/interface-spec/pull/51 to use named exported functions for callbacks.
This PR however puts the name-callbacks functionality into the system-api functions `ic0.call_new_name_callbacks` & `ic0.call_on_cleanup_name` as alternatives for `ic0.call_new` & `ic0.call_on_cleanup`.
Each call can use either `ic0.call_new` or `ic0.call_new_name_callbacks` but not both. Same for `ic0.call_on_cleanup` & `ic0.call_on_cleanup_name`.

This PR is backwards compatible.

### CODE REVIEW

**Comment by nomeata** [comment]
Cool, thanks!

Technically, I believe the old one is backwards compatible, as Wasm itself can handle importing and exporting functions with same names, as long as the types are different. But pragmatically, hoping that all tooling involved can do that too is probably not a good idea, so 👍

**Comment by levifeldman** [comment]
@nomeata The old one didn't leave room in the spec for canisters to continue registering callbacks with a table index and still be in sync with the spec.

**Comment by nomeata** [comment]
I think my idea was that the replica can support multiple API versions, i.e. one doesn't need “old” function signatures in the spec for them to still work. But keeping both around as officially supported is good, too!

**Comment by levifeldman** [comment]
Thanks for laying the groundwork for this feature @nomeata.

**Comment by levifeldman** [comment]
@Dfinity-Bjoern @manudrijvers @mraszyk @dsarlis What do you guys think?

**Comment by levifeldman** [comment]
@Dfinity-Bjoern @manudrijvers @mraszyk @dsarlis Feedback?

**Comment by Dfinity-Bjoern** [comment]
Closing the PR for now because there is no active work and it is unclear that converting it to markdown is beneficial at this point. The PR can be converted and reopened at any point in time, such as when the engineering teams actually have capacity to work on the implementation.

**Pull request closed without merging**
