### PR TITLE
fix: wrap chunk hash in a record and rename storage_canister to store_canister

### PR DESCRIPTION
**Pull request by mraszyk**
This PR wraps a chunk hash in the management canister API into a record with a single field containing the hash and renames `storage_canister` to `store_canister`.

### CODE REVIEW

**Comment by Dfinity-Bjoern** [comment]
I guess this is in order to reflect the interface that is actually implemented, but: Why?

**Comment by adambratschikaye** [comment]
When dealing with the API, it's not so intuitive what the `blob` returned by `upload_chunk` represents. So putting it in a labeled record makes it more user friendly.

**Comment by adambratschikaye** [comment]
^ merging that MR now.

**Comment by lwshang** [comment]
Since the IC MR has been merged, we can merge this PR now, right?

**Comment by lwshang** [comment]
There is still an inconsistent behavior between this interface-spec and the actual implementation.
The `chunk_hashes_list` field of `install_chunked_code`'s argument is different:
* In this spec: it is `vec chunk_hash` in which `type chunk_hash = record { hash : blob; };`
* In implementation: it is `vec vec nat8`

The implementation behavior was observed in Rust CDK CI using `ic-test-state-machine`. A sample failure can be found here:
https://github.com/dfinity/cdk-rs/actions/runs/8052621991/job/21993175798#step:5:1264

**Review by bogwar — APPROVED** [review]
thanks Martin

**Pull request merged**
