### PR TITLE
fix: Correct the naming of the trustworthy metric: node num_blocks_total

### PR DESCRIPTION
**Pull request by sasa-tomic**
The current name is confusing not only for me but also for the community member(s). I propose we change it to make it more specific.

image

link: https://matrix.to/#/!jUsknEqNdJobySpXuN:matrix.org/$wmamJVHU4QTXBWvNx-Rbq8NubEfHyAymhfdjMDsrWfU?via=matrix.org&via=greensteps.cn&via=rudd-o.com

### CODE REVIEW

**Comment by Dfinity-Bjoern** [comment]
Is this already in production? Then this would be a breaking change.

**Comment by sasa-tomic** [comment]
> Is this already in production? Then this would be a breaking change.

@Dfinity-Bjoern correct, but this feature is marked as experimental, so there is no better time to fix it than now.
Also, the only user of these metrics (that we know of) is the DRE tool.

**Comment by Dfinity-Bjoern** [comment]
Your right, thanks for pointing this out!

**Review by Dfinity-Bjoern — APPROVED** [review]

**Comment by mraszyk** [comment]
@sasa-tomic Please do not merge until the feature is rolled out in production.

**Comment by sasa-tomic** [comment]
The replica code change is in https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/19153

**Comment by mraszyk** [comment]
This feature is contained in the [upcoming](https://dashboard.internetcomputer.org/proposal/129746) IC release so merging this MR now.

**Pull request merged**
