### PR TITLE
feat: allow System API method in_replicated_execution to run during canister_start

### PR DESCRIPTION
**Pull request by maksymar**
This PR allows a system API method `in_replicated_execution` to be executed during `canister_start`.

### CODE REVIEW

**Review by mraszyk — CHANGES_REQUESTED** [review]
Could you please update this section https://khsfq-wqaaa-aaaak-qckvq-cai.icp0.io/docs#system-api-imports

**Comment by maksymar** [comment]
> Could you please update this section https://khsfq-wqaaa-aaaak-qckvq-cai.icp0.io/docs#system-api-imports

Done.

**Comment by maksymar** [comment]
> Is this already merged in the replica code? Then I could approve and we can merge this PR in (after updating the changelog).

I have an open [MR](https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/16630) for that.

**Review by dfinity-berestovskyy — APPROVED** [review]
LGTM, thanks!

**Review by ielashi — APPROVED** [review]

**Review by mraszyk — APPROVED** [review]
Thank you for updating the spec! @maksymar

**Pull request merged**
